### PR TITLE
Ft registration form

### PR DESCRIPTION
**Pull request by PetronilahKwamboka**
- Added registration form with image upload and form input elements
- Removed the image upload in sign-in form 
- Added bootstrap, CSS,  scripts links to register.HTML
- Added styles to registration form
- Removed function for uploading image in sign-in form

### CODE REVIEW

**Review by gkarumbi — APPROVED** [review]
Great code work, proceed to merge!

**Review by kangalah — APPROVED** [review]
Awesome work

**Review by tonyguthiga — APPROVED** [review]
Awesome job, l like the form.

**Review by MUTHAKABRIAN — APPROVED** [review]
Good job!! on the registration form.

**Pull request merged**
