### PR TITLE
Js register

### PR DESCRIPTION
**Pull request by MUTHAKABRIAN**
-Added constructor 
-Added submit function to collect data from register.HTML
-Function to collect image
-Implemented verify password on Register.HTML

### CODE REVIEW

**Review by gkarumbi — APPROVED** [review]
code looks good, proceed to merge!!

**Review by tonyguthiga — APPROVED** [review]
function looks great,congrats

**Review by PetronilahKwamboka — APPROVED** [review]
Nice one

**Review by kangalah — APPROVED** [review]
Well done with the functions.

**Pull request merged**
