### PR TITLE
Ft about us

### PR DESCRIPTION
**Pull request by PetronilahKwamboka**
Added h2 about us
Card deck with paragraphs
Padding-top to h2, font-size for paragraphs

### CODE REVIEW

**Review by gkarumbi — APPROVED** [review]
Looks okay to me, go ahead and merge!

**Comment by MUTHAKABRIAN** [comment]
good job done on cards in the about us section

**Comment by MUTHAKABRIAN** [comment]
Good job on the cards in the About us section

**Review by MUTHAKABRIAN — COMMENTED** [review]
Good job on the cards in the about us section..

**Review by MUTHAKABRIAN — APPROVED** [review]
Good job on the cards in the about us section..

**Comment by kangalah** [comment]
good job

**Pull request merged**
