### PR TITLE
Ft signin form

### PR DESCRIPTION
**Pull request by kangalah**
-Added a sign-in form.
-Added color to the anchor links.
-Removed the drop-down menu for contact-us.

### CODE REVIEW

**Comment by tonyguthiga** [comment]
Form looks awesome.Good job

**Review by gkarumbi — APPROVED** [review]
Looks okay, proceed to merge!

**Review by MUTHAKABRIAN — APPROVED** [review]
well done!!!! on the sign in form

**Review by tonyguthiga — APPROVED** [review]
Form looks awesome,good job

**Pull request merged**
