### PR TITLE
Ft homepage

### PR DESCRIPTION
**Pull request by MUTHAKABRIAN**
Added a background image and styled it
Sticky-top nav-bar
Styled h1 and h3

### CODE REVIEW

**Comment by tonyguthiga** [comment]
Excellent

**Comment by PetronilahKwamboka** [comment]
I like the homepage, nice one

**Comment by kangalah** [comment]
Good work.

**Comment by MUTHAKABRIAN** [comment]
/home/acebreezy/Desktop/Tenant-app/images.zip

**Pull request merged**
