### PR TITLE
Ft contact

### PR DESCRIPTION
**Pull request by tonyguthiga**
- Added contact.html
-Added background image
-Styled background image
-Created feedback form
-Styled H4 and paragraph
-Linked contact.html to index.html

### CODE REVIEW

**Comment by MUTHAKABRIAN** [comment]
great work done on contact.html,linking of the to page and styling of the form

**Review by PetronilahKwamboka — APPROVED** [review]
The contact form looks good, i like it

**Comment by MUTHAKABRIAN** [comment]
great work done on contact.html,linking of the to page and styling of the form

**Review by MUTHAKABRIAN — APPROVED** [review]
great work done on contact.html,linking of the to page and styling of the form

**Pull request merged**
