### PR TITLE
Ft profile

### PR DESCRIPTION
**Pull request by gkarumbi**
- Added cards to output registered users on the profile sections
-Added an array to store profile name objects

### CODE REVIEW

**Review by kangalah — APPROVED** [review]
Good work George

**Review by tonyguthiga — APPROVED** [review]
Great job on the code.

**Review by MUTHAKABRIAN — APPROVED** [review]
good job !!!.proceed to merge

**Review by PetronilahKwamboka — APPROVED** [review]
The cards look awesome, code looks good too

**Pull request merged**
